/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formTraza.java
 *
 * Created on Nov 14, 2009, 6:07:19 PM
 */

package antframework.app;
import antframework.common.Matrix;

/**
 *
 * @author enriqueareyan
 */
public class formTraza extends javax.swing.JFrame {
    protected Traza T;
    public panelGrafo P;
    protected int trazaActual = 0;
    /** Creates new form formTraza */
    public formTraza(Traza T,panelGrafo P) {
        this.T = T;
        this.P = P;
        initComponents();
        try{
            graficarTraza();
        }catch(Exception e){

        }
    }
public void graficarTraza() throws Exception{

    Matrix feromonas = this.T.getFeromona(this.trazaActual);
    /*feromonas.show();*/
    String tabla = "<html>" +
            "<table style='border:1px solid black;background-color:white;width:100%'>" +
            "<tr><td>&nbsp;</td>";
    /* grafica la traza i */
    for(int j=0;j<feromonas.getRows();j++){
        tabla = tabla + "<td>"+j+"</td>";
    }
    tabla = tabla + "</tr>";
    for(int j=0;j<feromonas.getRows();j++){
        tabla = tabla + "<tr><td>"+j+"</td>";
        for(int h=0;h<feromonas.getColumns();h++){
            tabla = tabla + "<td style='background-color:"+this.calcularColor(feromonas.position(j,h))+"'>&nbsp;&nbsp;&nbsp;</td>";
        }
        tabla = tabla + "</tr>";
    }
    tabla = tabla + "</table></html>";
    this.lblTraza.setText(tabla);
    this.lblTraza.setSize(500, 500);
    setTitle("Iteracion #"+this.T.i.get(this.trazaActual));
    //this.jLabel2.setText("<html><h4>Iteracion #"+this.T.i.get(this.trazaActual)+"</h4></html>");
    if(this.trazaActual == 0){
        botonAtras.setEnabled(false);
    }else{
        botonAtras.setEnabled(true);
    }
    if(this.trazaActual+1 == this.T.i.size()){
        botonAdelantar.setEnabled(false);
    }else{
        botonAdelantar.setEnabled(true);
    }
}
public String calcularColor(double valor){
    if(valor< 0.05){
        return "white";
    }else if(valor < 0.1){
        return "#E4E4E4";
    }else if(valor < 0.2){
        return "#D7D7D7";
    }else if(valor < 0.3){
        return "#C9C9C9";
    }else if(valor < 0.4){
        return "#C0C0C0";
    }else if(valor < 0.5){
        return "#B6B6B6";
    }else if(valor < 0.6){
        return "#9D9D9D";
    }else if(valor < 0.7){
        return "#7E7E7E";
    }else if(valor < 0.8){
        return "#585858";
    }else if(valor < 0.9){
        return "#333333";
    }else if(valor < 1){
        return "#181818";
    }
    return "black";
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAdelantar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblTraza = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonAdelantar.setText(">");
        botonAdelantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdelantarActionPerformed(evt);
            }
        });

        botonAtras.setText("<");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Saltar a:");

        jTextField1.setText("0");

        jButton1.setText("Saltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblTraza.setAutoscrolls(true);
        jScrollPane1.setViewportView(lblTraza);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(botonAtras)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(botonAdelantar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 321, Short.MAX_VALUE)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(botonAtras)
                    .add(botonAdelantar)
                    .add(jButton1)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAdelantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdelantarActionPerformed
        // TODO add your handling code here:
        if(trazaActual+1 < T.i.size()){
            this.trazaActual++;
            try{
                graficarTraza();
            }catch(Exception e){

            }
	}
}//GEN-LAST:event_botonAdelantarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        if(trazaActual-1 >= 0){
        	this.trazaActual--;
		try{
                    graficarTraza();
                }catch(Exception e){

                }
	}
}//GEN-LAST:event_botonAtrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int posAnterior = this.trazaActual;
        this.trazaActual = Integer.parseInt(this.jTextField1.getText());
        try{
            graficarTraza();
        }catch(Exception e){
            this.trazaActual = posAnterior;
            javax.swing.JOptionPane.showMessageDialog(this, "No existe la muestra a la que se quiere saltar:\n"+e.toString() ,"Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdelantar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblTraza;
    // End of variables declaration//GEN-END:variables

}
