/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Nov 13, 2009, 8:17:00 PM
 */

package antframework.app;
import java.io.*;
import antframework.common.Graph;
import javax.swing.JPanel;

/**
 *
 * @author enriqueareyan
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main() {
        initComponents();
        this.setSize(850, 680);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarArchivos = new javax.swing.JFileChooser();
        dialogoAcerca = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        dialogoNuevoGrafo = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreNuevoGrafo = new javax.swing.JTextField();
        cantNodosNuevoGrafo = new javax.swing.JSpinner();
        botonCrearGrafo = new javax.swing.JButton();
        panelPestanaPrincipal = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        dialogoAcerca.setTitle("Acerca de...");
        dialogoAcerca.setResizable(false);

        jLabel1.setText("<html><div style='text-align:center'><h1 style='font-weight:bold;text-decoration:underline'>AntFramework v1.0</h1><h2>Aplicación demostrativa del Framework basado en Colonias de Hormigas</h2> <h3>Creado por Enrique Areyán, como Trabajo Especial de Grado presentado ante la</h3> <h3>Universidad Central de Venezuela <br>Facultad de Ciencias<br> Escuela de Computación</h3> </div> </html>");

        org.jdesktop.layout.GroupLayout dialogoAcercaLayout = new org.jdesktop.layout.GroupLayout(dialogoAcerca.getContentPane());
        dialogoAcerca.getContentPane().setLayout(dialogoAcercaLayout);
        dialogoAcercaLayout.setHorizontalGroup(
            dialogoAcercaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        dialogoAcercaLayout.setVerticalGroup(
            dialogoAcercaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        dialogoNuevoGrafo.setTitle("Crear nuevo grafo");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("# Nodos:");

        cantNodosNuevoGrafo.setModel(new javax.swing.SpinnerNumberModel(2, 2, 100, 1));

        botonCrearGrafo.setText("Crear Grafo");
        botonCrearGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearGrafoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout dialogoNuevoGrafoLayout = new org.jdesktop.layout.GroupLayout(dialogoNuevoGrafo.getContentPane());
        dialogoNuevoGrafo.getContentPane().setLayout(dialogoNuevoGrafoLayout);
        dialogoNuevoGrafoLayout.setHorizontalGroup(
            dialogoNuevoGrafoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogoNuevoGrafoLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogoNuevoGrafoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogoNuevoGrafoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cantNodosNuevoGrafo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtNombreNuevoGrafo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialogoNuevoGrafoLayout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .add(botonCrearGrafo)
                .addContainerGap())
        );

        dialogoNuevoGrafoLayout.linkSize(new java.awt.Component[] {jLabel2, jLabel3}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        dialogoNuevoGrafoLayout.setVerticalGroup(
            dialogoNuevoGrafoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialogoNuevoGrafoLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialogoNuevoGrafoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txtNombreNuevoGrafo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialogoNuevoGrafoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(cantNodosNuevoGrafo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                .add(botonCrearGrafo)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AntFramework v1.0");

        jEditorPane1.setEditable(false);
        jEditorPane1.setText("Instrucciones de uso:\n\nCargar Grago:\nPara cargar un nuevo grafo, haga clic en el menu \"Opciones\"->\"Cargar Grafo\".\n\nUn grafo válido es una matriz de adyacencia contenida en un archivo de texto plano \"·txt\", en el cual las primeras dos líneas indican la dimension de la matriz  y las siguientes n lineas las adyacencias entre cada par de nodos (i, j). \nEl siguiente es un ejemplo de una matriz de adyacencia para un grafo de 5 nodos:\n\n5\n5\n0.0\t5.0\t5.0\t3.0\t4.0\t\n4.0\t0.0\t2.0\t3.0\t1.0\t\n3.0\t1.0\t0.0\t1.0\t3.0\t\n1.0\t3.0\t2.0\t0.0\t4.0\t\n3.0\t4.0\t1.0\t2.0\t0.0\t\n\nNuevo Grafo:\nEsta opción permite crear un grafo en línea. Se desplegará una ventana en donde deberá escribir el nombre del grafo, y la cantidad de nodos.\nUna vez escrita esa información, se le presentará una pantalla similar a la de la opción Cargar Grafo, en donde podrá visualizar una matriz de adyacencia sólo con ceros.\nUsted deberá rellenar las casillas de cada nodo (i, j) de dicha matriz de adyacencia para crear un grafo válido. Una vez realizado este proceso, el grafo está listo para ejecutarse.\n\n");
        jEditorPane1.setFocusable(false);
        jScrollPane1.setViewportView(jEditorPane1);

        org.jdesktop.layout.GroupLayout panelInicioLayout = new org.jdesktop.layout.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        panelPestanaPrincipal.addTab("Inicio", panelInicio);

        jMenu1.setText("Opciones");

        jMenuItem3.setText("Nuevo Grafo...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Cargar Grafo...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Acerca...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        Menu.add(jMenu1);

        setJMenuBar(Menu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelPestanaPrincipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelPestanaPrincipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void eliminarTab(JPanel panel){
        this.panelPestanaPrincipal.remove(panel);
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        /* Desplegar el seleccionador de archivos */
        int returnVal = seleccionarArchivos.showOpenDialog(this/*this.panelGrafo*/);
       /* Entra en este if si el usuario selecciono algo */
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            //El usuario selecciono un archivo
            File file = seleccionarArchivos.getSelectedFile();
            //System.out.println("Opening: " + file.getPath());
            try{
                /* Intentar Cargar el archivo, y crear el panel para ejecutarlo*/
                this.panelPestanaPrincipal.add(new panelGrafo(this,file.getName(),new Graph(file.getPath())));
                /* Seleccionar la pestana recien creada*/
                this.panelPestanaPrincipal.setSelectedIndex(this.panelPestanaPrincipal.getTabCount()-1);
            }catch(Exception e){
                /* Ocurrio un error, reportarlo */
                System.out.println("Error cargando grafo = "+e);
                //reportarError("<html><div style='text-align:center'><h1 style='font-weight:bold;text-decoration:underline'>Advertencia</h1><h2>Error Cargando Grafo</h2><h3>Por favor chequee que el archivo seleccionado cumpla con el formato necesario</h3><h4>"+ file.getPath()+" </h4></div></html>");
                reportarError("Error Cargando Grafo\n Por favor chequee que el archivo seleccionado cumpla con el formato necesario\n "+ file.getPath(),javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            //El usuario cancelo la seleccion de un archivo
            //System.out.println("Open command cancelled by user.");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dialogoAcerca.setSize(500, 300);
        this.dialogoAcerca.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void botonCrearGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearGrafoActionPerformed
        // TODO add your handling code here:
        /*inicializar el nuevo grafo con -1 en la diagonal */
        int cantNodos = Integer.parseInt(this.cantNodosNuevoGrafo.getValue().toString());
        double[] d = new double[cantNodos*cantNodos];
        for(int i=0;i<cantNodos;i++)
        	for(int j=0;j<cantNodos;j++)
                	d[i*cantNodos + j] = i==j?-1.0:1.0;
        /* agregar la pestana del nuevo grafo al panel principal */
        this.panelPestanaPrincipal.add(new panelGrafo(this,(this.txtNombreNuevoGrafo.getText().equals("")) ? "nuevo grafo":this.txtNombreNuevoGrafo.getText(),new Graph(cantNodos,cantNodos,d)));
        this.dialogoNuevoGrafo.setVisible(false);
        this.panelPestanaPrincipal.setSelectedIndex(this.panelPestanaPrincipal.getTabCount()-1);
    }//GEN-LAST:event_botonCrearGrafoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //this.dialogoNuevoGrafo.setVisible(true);
        //this.dialogoNuevoGrafo.pack();
		String nodes = javax.swing.JOptionPane.showInputDialog(this, "Introduzca el numero de nodos");
		if(nodes == null){
			return ;
		}

		int n = Integer.parseInt(nodes);
		int ret = seleccionarArchivos.showSaveDialog(this);
		if(ret == javax.swing.JFileChooser.APPROVE_OPTION){
			File file = seleccionarArchivos.getSelectedFile();
			//escribir el grafo en el archivo
			double[] d = new double[n*n];
			for(int i=0;i<n;i++)
				for(int j=0;j<n;j++)
                	d[i*n + j] = i==j?-1.0:1.0;

			try{
				Graph graph = new Graph(n,n,d);
				graph.save(file.getAbsolutePath());
                                graph.setFileSource(file.getAbsolutePath());

				this.panelPestanaPrincipal.add(new panelGrafo(this,file.getName(),graph));
				this.panelPestanaPrincipal.setSelectedIndex(this.panelPestanaPrincipal.getTabCount()-1);
			}catch(Exception e){
			}
		}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

	public void reportarError(String error,int tipo){
        //TODO: cambiar los mensajes de error por JOptionPane sin html.
        javax.swing.JOptionPane.showMessageDialog(this, error, "Advertencia" ,  tipo);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton botonCrearGrafo;
    private javax.swing.JSpinner cantNodosNuevoGrafo;
    private javax.swing.JDialog dialogoAcerca;
    private javax.swing.JDialog dialogoNuevoGrafo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JTabbedPane panelPestanaPrincipal;
    private javax.swing.JFileChooser seleccionarArchivos;
    private javax.swing.JTextField txtNombreNuevoGrafo;
    // End of variables declaration//GEN-END:variables

}
